defaultSemverRangePrefix: ""

npmAuthToken: "${NPM_TOKEN-}"

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
    spec: "https://raw.githubusercontent.com/sachinraja/yarn-plugin-postinstall-dev/main/bundles/%40yarnpkg/plugin-postinstall-dev.js"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.0.2.cjs
