name: Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build
        run: yarn build:ci

      - name: Lint
        run: yarn lint

      - name: Release
        id: release
        if: github.event_name == 'push'
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: node

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn npm publish
